### PR TITLE
Add support for irrational directions

### PR DESCRIPTION
**Pull request by turnip314**

### CODE REVIEW

**Comment by behackl** [comment]
I've resolved the merge conflicts, but this PR appears to introduce a serious regression: on my machine, tests pass in ~8sec on the main branch, and take ~3min on this branch.

I did not investigate this closer yet -- but I think this should be fixed before these changes are merged.

**Comment by behackl** [comment]
Meanwhile, I took a somewhat closer look. There is one particularly affected example.

Main branch:
```
Trying (line 78):    asy = diagonal_asy(
        1/(1 - w*(1 + x)*(1 + y)*(1 + z)*(x*y*z + y*z + y + z + 1))
    )
Expecting nothing
ok [0.19 s]
```

This PR:
```
Trying (line 78):    asy = diagonal_asy(
        1/(1 - w*(1 + x)*(1 + y)*(1 + z)*(x*y*z + y*z + y + z + 1))
    )
Expecting nothing
ok [165.85 s]
```

And upon further investigation, most of the time is actually spent computing the determinant of the Hessian. This feels a little silly, I'll try to find a workaround.

**Comment by behackl** [comment]
Pushed a rather simple workaround via 1e4305b -- the components of `r` (and the ratios computed in the code for determining the Hessian) are now kept in `QQ`, if possible.

The "large" example above takes a _long_ time with actually irrational directions. I'd have to experiment, but perhaps it would be more efficient to compute the Hessian for given critical points instead of over a fraction field of a multivariate polynomial ring over AA / QQbar. I'd leave the implementation as-is for now, though.

I'll continue reviewing this, but I have already noticed that the docstrings for `r` will have to be updated to reflect that not just positive integers are allowed, and at least one tested example for an irrational direction should be added. Do you have some sort of canonical example, or should we just go for something like `1/(1 - (x + y))` in direction `r=(sqrt(2), 1)`?

**Comment by smelczer** [comment]
The support for irrational directions was mainly added to support the computation of local limit theorems for multivariate generating functions. A concrete example of this that could be used in tests could be `1/(1-t-z*t^2)` in the direction `1/2-1/2*sqrt(1/5)` (which comes from a limit theorem for permutations with restricted cycles).

**Comment by behackl** [comment]
Fun! I'll just add both of them; is the full direction for the first case `r=(1/2-1/2*sqrt(1/5), 1)`?

There are some more improvements that I'd like to make in terms of readability, but otherwise the changes here look fine to me. Will probably manage either later today or tomorrow / early next week.

**Comment by smelczer** [comment]
This is part of a family of limit theorems -- if you want something in higher dimension see Theorem 22 in https://arxiv.org/abs/2211.15492 (the one in my previous message happens when d=1).

**Comment by behackl** [comment]
I did a careful refactor of the changed bits and pieces of the implementation of `MinimalCriticalCombinatorial` in 343039b to make the code more readable.

Tests have been added and the docstrings fixed -- if the pipeline passes this is good to be merged in my opinion.

**Pull request merged**
